language: go

os: linux
dist: bionic
go: 1.14.x

cache:
  directories:
    - ${HOME}/.cache/go-build
    - ${GOPATH}/pkg/mod
    - ${GOPATH}/bin

env:
  global:
    - GCR_REPO: ${HOME}/gcr

stages:
  - Build imgsync
  - Sync Kubeadm
  - Sync Flannel
  - Sync Helm
  - Sync Istio
  - Sync Distroless
  - Sync Samples
  - Sync Linkerd
  - Sync Spinnaker
  - Sync KNative

before_script:
  - bash .travis-before.sh

jobs:
  include:
    - name: Build imgsync
      stage: Build imgsync
      script:
        - make install
    - name: Sync gcr
      stage: Sync gcr
      script:
        - imgsync gcr --user ${DOCKER_USER} --password ${DOCKER_PASSWORD}


after_success:
  - bash .travis-after-success.sh
